cmake_minimum_required(VERSION 3.30)
project(cpp_primer CXX)

set(CMAKE_CXX_STANDARD 11)

add_executable(cpp_primer
        #   ch_01/Sales_item.h
        #   ch_01/ex_01.cpp
        #   ch_01/ex_02.cpp
        #   ch_01/ex_03.cpp
        #   ch_01/ex_04.cpp
        #   ch_01/ex_05.cpp
        #   ch_01/ex_07.cpp
        #   ch_01/ex_08.cpp
        #   ch_01/ex_09.cpp
        #   ch_01/ex_10.cpp
        #   ch_01/ex_11.cpp
        #   ch_01/ex_13.cpp
        #   ch_01/ex_15.cpp
        #   ch_01/ex_16.cpp
        #   ch_01/ex_18.cpp
        #   ch_01/ex_19.cpp
        #   ch_01/ex_20.cpp
        #   ch_01/ex_21.cpp
        #   ch_01/ex_22.cpp
        #   ch_01/ex_23.cpp
        #   ch_01/ex_24.cpp
        #   ch_01/ex_25.cpp
        #   ch_02/ex_04.cpp
        #   ch_02/ex_08.cpp
        #   ch_02/ex_10.cpp
        #   ch_02/ex_13.cpp
        #   ch_02/ex_14.cpp
        #   ch_02/ex_18.cpp
        #   ch_02/ex_34.cpp
        #   ch_02/ex_35.cpp
        #   ch_02/ex_39.cpp
        #   ch_02/ex_40.cpp
        #   ch_02/ex_41_1.cpp
        #   ch_02/ex_41_2.cpp
        #   ch_02/ex_41_3.cpp
        #   ch_02/ex_42_1.cpp
        #   ch_02/ex_42_2.cpp
        #   ch_02/ex_42_3.cpp
        #   ch_03/ex_01.cpp
        #   ch_03/ex_02.cpp
        #   ch_03/ex_04.cpp
        #   ch_03/ex_05.cpp
        #   ch_03/ex_06.cpp
        #   ch_03/ex_08.cpp
        #   ch_03/ex_10.cpp
        #   ch_03/ex_14.cpp
        #   ch_03/ex_15.cpp
        #   ch_03/ex_16.cpp
        #   ch_03/ex_17.cpp
        #   ch_03/ex_19.cpp
        #   ch_03/ex_20.cpp
        #   ch_03/ex_21.cpp
        #   ch_03/ex_22.cpp
        #   ch_03/ex_23.cpp
        #   ch_03/ex_24.cpp
        #   ch_03/ex_25.cpp
        #   ch_03/ex_31.cpp
        #   ch_03/ex_32_01.cpp
        #   ch_03/ex_32_02.cpp
        #   ch_03/ex_35.cpp
        #   ch_03/ex_36_01.cpp
        #   ch_03/ex_36_02.cpp
        #   ch_03/ex_39_01.cpp
        #   ch_03/ex_39_02.cpp
        #   ch_03/ex_40.cpp
        #   ch_03/ex_41.cpp
        #   ch_03/ex_42.cpp
        #   ch_03/ex_43.cpp
        #   ch_03/ex_44.cpp
        #   ch_03/ex_45.cpp
        #   ch_04/ex_04.cpp
        #   ch_04/ex_05.cpp
        #   ch_04/ex_06.cpp
        #   ch_04/ex_07.cpp
        #   ch_04/ex_10.cpp
        #   ch_04/ex_11.cpp
        #   ch_04/ex_21.cpp
        #   ch_04/ex_22.cpp
        #   ch_04/ex_23.cpp
        #   ch_04/ex_28.cpp
        #   ch_04/ex_29.cpp
        #   ch_05/ex_05.cpp
        #   ch_05/ex_06.cpp
        #   ch_05/ex_09.cpp
        #   ch_05/ex_10.cpp
        #   ch_05/ex_11.cpp
        #   ch_05/ex_12.cpp
        #   ch_05/ex_14.cpp
        #   ch_05/ex_17.cpp
        #   ch_05/ex_19.cpp
        #   ch_05/ex_20.cpp
        #   ch_05/ex_21.cpp
        #   ch_05/ex_23.cpp
        #   ch_05/ex_24.cpp
        #   ch_05/ex_25.cpp
        #   ch_06/ex_03.cpp
        #   ch_06/ex_04.cpp
        #   ch_06/ex_05.cpp
        #   ch_06/ex_07.cpp
#        ch_06/ch_06.h
#        ch_06/ex_09/fact.cc
#        ch_06/ex_09/factMain.cc
#        ch_06/ex_10.cpp
#        ch_06/ex_11.cpp
#        ch_06/ex_12.cpp
#        ch_06/ex_17.cpp
#        ch_06/ex_21.cpp
#        ch_06/ex_22.cpp
#        ch_06/ex_23.cpp
#        ch_06/ex_25.cpp
#        ch_06/ex_26.cpp
#        ch_06/ex_27.cpp
#        ch_06/ex_30.cpp
#        ch_06/ex_33.cpp
#        ch_06/ex_42.cpp
#        ch_06/ex_44.h
#        ch_06/ex_45.h
#        ch_06/ex_47.cpp
#        ch_06/ex_51.cpp
#        ch_06/ex_55.cpp
        # ch_06/ex_56.cpp
        # ch_07/ex_01.cpp
        # ch_07/ex_02.cpp
        # ch_07/ex_03.cpp
        # ch_07/ex_04.cpp
        # ch_07/ex_05.cpp
        # ch_07/ex_06.cpp
        # ch_07/ex_07.cpp
        # ch_07/ex_09.cpp
        # ch_07/ex_11.cpp
        # ch_07/ex_12.cpp
        # ch_07/ex_13.cpp
        # ch_07/ex_14.cpp
        # ch_07/ex_15.cpp
        # ch_07/ex_21.cpp
        # ch_07/ex_27.cpp
        # ch_07/ex_29.cpp
        # ch_07/ex_32.cpp
        # ch_07/ex_41.cpp
        # "ch_08/ex_01_02.cpp" 
        # "ch_08/ex_04.cpp"
        # "ch_08/ex_05.cpp"
        # "ch_08/ex_06.cpp" 
        # "ch_08/ex_07.cpp" 
        # "ch_08/ex_08.cpp" 
        # "ch_08/ex_09.cpp" 
        # "ch_08/ex_10.cpp" 
        # "ch_08/ex_11.cpp" 
        # "ch_08/ex_13.cpp" 
        # "ch_09/ex_04.cpp" 
        # "ch_09/ex_05.cpp" 
        # "ch_09/ex_11.cpp" 
        # "ch_09/ex_13.cpp"
        # "ch_09/ex_14.cpp"
        # "ch_09/ex_15.cpp" 
        # "ch_09/ex_16.cpp"  
        # "ch_09/ex_18.cpp" 
        # "ch_09/ex_19.cpp" 
        # "ch_09/ex_20.cpp"  
        # "ch_09/ex_24.cpp" 
        # "ch_09/ex_26.cpp" 
        # "ch_09/ex_27.cpp" 
        # "ch_09/ex_28.cpp"  
        # "ch_09/ex_31.cpp"    
        # "ch_09/ex_38.cpp" 
        # "ch_09/ex_41.cpp" 
        # "ch_09/ex_43.cpp" 
        # "ch_09/ex_44.cpp" 
        # "ch_09/ex_45.cpp" 
        # "ch_09/ex_46.cpp" 
        # "ch_09/ex_47.cpp" 
        # "ch_09/ex_49.cpp" 
        # "ch_09/ex_50.cpp"  
        # "ch_09/ex_52.cpp" 
        # "ch_10/ex_01.cpp" 
        # "ch_10/ex_02.cpp" 
        # "ch_10/ex_03.cpp" 
        # "ch_10/ex_05.cpp" 
        # "ch_10/ex_06.cpp" 
        # "ch_10/ex_07.cpp" 
        # "ch_10/ex_09.cpp" 
        # "ch_10/ex_11.cpp" 
        # "ch_10/ex_12.cpp" 
        # "ch_10/ex_13.cpp" 
        # "ch_10/ex_14.cpp" 
        # "ch_10/ex_15.cpp" 
        # "ch_10/ex_16.cpp" 
        # "ch_10/ex_17.cpp" 
        # "ch_10/ex_18.cpp" 
        # "ch_10/ex_19.cpp" 
        # "ch_10/ex_20.cpp" 
        # "ch_10/ex_21.cpp" 
        # "ch_10/ex_22.cpp" 
        # "ch_10/ex_24.cpp" 
        # "ch_10/ex_25.cpp" 
        # "ch_10/ex_27.cpp" 
        # "ch_10/ex_28.cpp" 
        # "ch_10/ex_29.cpp" 
        # "ch_10/ex_30.cpp" 
        # "ch_10/ex_31.cpp" 
        # "ch_10/ex_32.cpp" 
        # "ch_10/ex_33.cpp" 
        # "ch_10/ex_34.cpp" 
        # "ch_10/ex_35.cpp" 
        # "ch_10/ex_36.cpp" 
        # "ch_10/ex_37.cpp" 
        # "ch_10/ex_42.cpp" 
        # "ch_11/ex_03.cpp" 
        # "ch_11/ex_04.cpp" 
        # "ch_11/ex_07.cpp" 
        # "ch_11/ex_08.cpp" 
        # "ch_11/ex_09.cpp"
        # "ch_11/ex_12.cpp" 
        # "ch_11/ex_13.cpp" 
        # "ch_11/ex_14.cpp"
        # "ch_11/ex_17.cpp"
        # "ch_11/ex_18.cpp"
        # ch_11/ex_20.cpp
        # ch_11/ex_23.cpp
        # ch_11/ex_31.cpp
        # ch_11/ex_32.cpp
        # ch_11/ex_33.cpp
        # ch_11/ex_38_1.cpp
        # ch_11/ex_38_2.cpp
        # ch_12/ex_02.cpp
        # ch_12/ex_06.cpp
        # ch_12/ex_07.cpp
        # ch_12/ex_14.cpp
        # ch_12/ex_15.cpp
        # ch_12/ex_16.cpp
        # ch_12/ex_19.cpp
        # ch_12/ex_19.h
        # ch_12/ex_20.cpp
        # ch_12/ex_22.cpp
        # ch_12/ex_22.h
        # ch_12/ex_23.cpp
        # ch_12/ex_24.cpp
        # ch_12/ex_26.cpp
        # ch_12/ex_27.h
        # ch_12/ex_27.cpp
        # ch_12/ex_28.cpp
        # ch_12/ex_29.cpp
        # ch_12/ex_30.cpp
        # ch_12/ex_30.h
        # ch_12/ex_32.cpp
        # ch_12/ex_32.h
        # ch_13/ex_05.cpp
        # ch_13/ex_08.cpp
        # ch_13/ex_11.cpp
        # ch_13/ex_13.cpp
        # ch_13/ex_14.cpp
        # ch_13/ex_15.cpp
        # ch_13/ex_16.cpp
        # ch_13/ex_18.cpp
        # ch_13/ex_19.cpp
        # ch_13/ex_22.cpp
        # ch_13/ex_26.h
        # ch_13/ex_27.cpp
        # ch_13/ex_28.cpp
        # ch_13/ex_30.cpp
        # ch_13/ex_31.cpp
        # ch_13/ex_34.cpp
        # ch_13/ex_36.cpp
        # ch_13/ex_36.h
        # ch_13/ex_39_40.cpp
        # ch_13/ex_39_40.h
        # ch_13/ex_42.cpp
        # ch_13/ex_42.h
        # ch_13/ex_44.h
        # ch_13/ex_44.cpp
        # ch_13/ex_47_48.cpp
        # ch_13/ex_47_48.h
        # ch_13/ex_50.cpp
        # ch_13/ex_50.h
        # ch_13/ex_53.cpp
        # ch_13/ex_58.cpp
#        ch_14/ex_05_08_12_17_19.cpp
#        ch_14/ex_16_StrBlob_StrBlobPtr.cpp
#        ch_14/ex_16_StrVec.cpp
#        ch_14/ex_16_MyString.cpp
#        ch_14/ex_02_06_09_10_11_13.cpp
#        ch_14/ex_30.cpp
#        ch_14/ex_34_35_36.cpp
#        ch_14/ex_37.cpp
#        ch_14/ex_38_39.cpp
#        ch_14/ex_40.cpp
#        ch_14/ex_44.cpp
#        ch_15/ex_03.cpp
#        ch_15/ex_05.cpp
#        ch_15/ex_Disc_quote_Bulk_quote_15_16_17.cpp
#        ch_15/ex_20.cpp
#        ch_15/ex_21.cpp
#        ch_15/ex_26_27_28_29.cpp
#        ch_15/ex_30.cpp
#        ch_16/ex_02_03.cpp
#        ch_16/ex_04.cpp
#        ch_16/ex_05.cpp
#        ch_16/ex_06.cpp
#        ch_16/ex_07.cpp
#        ch_16/ex_12_24_29.cpp
#        ch_16/ex_14.cpp
#        ch_16/ex_16.cpp
#        ch_16/ex_19_20.cpp
#        ch_16/ex_21_22.cpp
#        ch_16/ex_28.cpp
#        ch_16/ex_39.cpp
#        ch_16/ex_47.cpp
#        ch_16/ex_48.cpp
#        ch_16/ex_49_50.cpp
#        ch_16/ex_51_52.cpp
#        ch_16/ex_53.cpp
#        ch_16/ex_56.cpp
#        ch_16/ex_58.cpp
#        ch_16/ex_62.cpp
#        ch_16/ex_63_64.cpp
        ch_16/ex_65.cpp
)

target_compile_options(cpp_primer PRIVATE 
    $<$<CXX_COMPILER_ID:MSVC>:/W4 /permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall -Wextra -pedantic -pedantic-errors>
)

install(TARGETS cpp_primer RUNTIME DESTINATION ${CMAKE_SOURCE_DIR})
